spring:
  application:
    name: social-network
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/socialnetwork"
    username: baeldung
    password: baeldung
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
